//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DXWebTemplate.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService2Soap", Namespace="http://tempuri.org/")]
    public partial class WebService2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback Upload_DataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitmeterOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitwaterapplicantOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitdetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SummitauthoritiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendapproveOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubmitapproveOperationCompleted;
        
        private System.Threading.SendOrPostCallback approveOperationCompleted;
        
        private System.Threading.SendOrPostCallback waterusernumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback view_user_waterOperationCompleted;
        
        private System.Threading.SendOrPostCallback List_petition_informationOperationCompleted;
        
        private System.Threading.SendOrPostCallback List_MeterOperationCompleted;
        
        private System.Threading.SendOrPostCallback List_water_applicantOperationCompleted;
        
        private System.Threading.SendOrPostCallback List_detailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback List_authoritiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback List_approveOperationCompleted;
        
        private System.Threading.SendOrPostCallback Search_water_userOperationCompleted;
        
        private System.Threading.SendOrPostCallback Search_requst_instalOperationCompleted;
        
        private System.Threading.SendOrPostCallback search_approve_requestOperationCompleted;
        
        private System.Threading.SendOrPostCallback ViewGps_LocationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService2() {
            this.Url = global::DXWebTemplate.Properties.Settings.Default.DXWebTemplate_WebReference_WebService2;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event Upload_DataCompletedEventHandler Upload_DataCompleted;
        
        /// <remarks/>
        public event SubmitCompletedEventHandler SubmitCompleted;
        
        /// <remarks/>
        public event SubmitmeterCompletedEventHandler SubmitmeterCompleted;
        
        /// <remarks/>
        public event SubmitwaterapplicantCompletedEventHandler SubmitwaterapplicantCompleted;
        
        /// <remarks/>
        public event SubmitdetailsCompletedEventHandler SubmitdetailsCompleted;
        
        /// <remarks/>
        public event SummitauthoritiesCompletedEventHandler SummitauthoritiesCompleted;
        
        /// <remarks/>
        public event SendapproveCompletedEventHandler SendapproveCompleted;
        
        /// <remarks/>
        public event SubmitapproveCompletedEventHandler SubmitapproveCompleted;
        
        /// <remarks/>
        public event approveCompletedEventHandler approveCompleted;
        
        /// <remarks/>
        public event waterusernumberCompletedEventHandler waterusernumberCompleted;
        
        /// <remarks/>
        public event view_user_waterCompletedEventHandler view_user_waterCompleted;
        
        /// <remarks/>
        public event List_petition_informationCompletedEventHandler List_petition_informationCompleted;
        
        /// <remarks/>
        public event List_MeterCompletedEventHandler List_MeterCompleted;
        
        /// <remarks/>
        public event List_water_applicantCompletedEventHandler List_water_applicantCompleted;
        
        /// <remarks/>
        public event List_detailsCompletedEventHandler List_detailsCompleted;
        
        /// <remarks/>
        public event List_authoritiesCompletedEventHandler List_authoritiesCompleted;
        
        /// <remarks/>
        public event List_approveCompletedEventHandler List_approveCompleted;
        
        /// <remarks/>
        public event Search_water_userCompletedEventHandler Search_water_userCompleted;
        
        /// <remarks/>
        public event Search_requst_instalCompletedEventHandler Search_requst_instalCompleted;
        
        /// <remarks/>
        public event search_approve_requestCompletedEventHandler search_approve_requestCompleted;
        
        /// <remarks/>
        public event ViewGps_LocationCompletedEventHandler ViewGps_LocationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Upload_Data", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Upload_Data(string jsonString) {
            object[] results = this.Invoke("Upload_Data", new object[] {
                        jsonString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Upload_DataAsync(string jsonString) {
            this.Upload_DataAsync(jsonString, null);
        }
        
        /// <remarks/>
        public void Upload_DataAsync(string jsonString, object userState) {
            if ((this.Upload_DataOperationCompleted == null)) {
                this.Upload_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpload_DataOperationCompleted);
            }
            this.InvokeAsync("Upload_Data", new object[] {
                        jsonString}, this.Upload_DataOperationCompleted, userState);
        }
        
        private void OnUpload_DataOperationCompleted(object arg) {
            if ((this.Upload_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Upload_DataCompleted(this, new Upload_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Submit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Submit(string jsonString) {
            object[] results = this.Invoke("Submit", new object[] {
                        jsonString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitAsync(string jsonString) {
            this.SubmitAsync(jsonString, null);
        }
        
        /// <remarks/>
        public void SubmitAsync(string jsonString, object userState) {
            if ((this.SubmitOperationCompleted == null)) {
                this.SubmitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitOperationCompleted);
            }
            this.InvokeAsync("Submit", new object[] {
                        jsonString}, this.SubmitOperationCompleted, userState);
        }
        
        private void OnSubmitOperationCompleted(object arg) {
            if ((this.SubmitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitCompleted(this, new SubmitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Submitmeter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Submitmeter(string id_petition_information, string jsonString) {
            object[] results = this.Invoke("Submitmeter", new object[] {
                        id_petition_information,
                        jsonString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitmeterAsync(string id_petition_information, string jsonString) {
            this.SubmitmeterAsync(id_petition_information, jsonString, null);
        }
        
        /// <remarks/>
        public void SubmitmeterAsync(string id_petition_information, string jsonString, object userState) {
            if ((this.SubmitmeterOperationCompleted == null)) {
                this.SubmitmeterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitmeterOperationCompleted);
            }
            this.InvokeAsync("Submitmeter", new object[] {
                        id_petition_information,
                        jsonString}, this.SubmitmeterOperationCompleted, userState);
        }
        
        private void OnSubmitmeterOperationCompleted(object arg) {
            if ((this.SubmitmeterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitmeterCompleted(this, new SubmitmeterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Submitwaterapplicant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Submitwaterapplicant(string id_petition_information, string jsonString) {
            object[] results = this.Invoke("Submitwaterapplicant", new object[] {
                        id_petition_information,
                        jsonString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitwaterapplicantAsync(string id_petition_information, string jsonString) {
            this.SubmitwaterapplicantAsync(id_petition_information, jsonString, null);
        }
        
        /// <remarks/>
        public void SubmitwaterapplicantAsync(string id_petition_information, string jsonString, object userState) {
            if ((this.SubmitwaterapplicantOperationCompleted == null)) {
                this.SubmitwaterapplicantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitwaterapplicantOperationCompleted);
            }
            this.InvokeAsync("Submitwaterapplicant", new object[] {
                        id_petition_information,
                        jsonString}, this.SubmitwaterapplicantOperationCompleted, userState);
        }
        
        private void OnSubmitwaterapplicantOperationCompleted(object arg) {
            if ((this.SubmitwaterapplicantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitwaterapplicantCompleted(this, new SubmitwaterapplicantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Submitdetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Submitdetails(string id_petition_information, string jsonString) {
            object[] results = this.Invoke("Submitdetails", new object[] {
                        id_petition_information,
                        jsonString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitdetailsAsync(string id_petition_information, string jsonString) {
            this.SubmitdetailsAsync(id_petition_information, jsonString, null);
        }
        
        /// <remarks/>
        public void SubmitdetailsAsync(string id_petition_information, string jsonString, object userState) {
            if ((this.SubmitdetailsOperationCompleted == null)) {
                this.SubmitdetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitdetailsOperationCompleted);
            }
            this.InvokeAsync("Submitdetails", new object[] {
                        id_petition_information,
                        jsonString}, this.SubmitdetailsOperationCompleted, userState);
        }
        
        private void OnSubmitdetailsOperationCompleted(object arg) {
            if ((this.SubmitdetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitdetailsCompleted(this, new SubmitdetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Summitauthorities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Summitauthorities(string id_petition_information, string jsonString) {
            object[] results = this.Invoke("Summitauthorities", new object[] {
                        id_petition_information,
                        jsonString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SummitauthoritiesAsync(string id_petition_information, string jsonString) {
            this.SummitauthoritiesAsync(id_petition_information, jsonString, null);
        }
        
        /// <remarks/>
        public void SummitauthoritiesAsync(string id_petition_information, string jsonString, object userState) {
            if ((this.SummitauthoritiesOperationCompleted == null)) {
                this.SummitauthoritiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSummitauthoritiesOperationCompleted);
            }
            this.InvokeAsync("Summitauthorities", new object[] {
                        id_petition_information,
                        jsonString}, this.SummitauthoritiesOperationCompleted, userState);
        }
        
        private void OnSummitauthoritiesOperationCompleted(object arg) {
            if ((this.SummitauthoritiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SummitauthoritiesCompleted(this, new SummitauthoritiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Sendapprove", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Sendapprove(string id_petition_information) {
            object[] results = this.Invoke("Sendapprove", new object[] {
                        id_petition_information});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendapproveAsync(string id_petition_information) {
            this.SendapproveAsync(id_petition_information, null);
        }
        
        /// <remarks/>
        public void SendapproveAsync(string id_petition_information, object userState) {
            if ((this.SendapproveOperationCompleted == null)) {
                this.SendapproveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendapproveOperationCompleted);
            }
            this.InvokeAsync("Sendapprove", new object[] {
                        id_petition_information}, this.SendapproveOperationCompleted, userState);
        }
        
        private void OnSendapproveOperationCompleted(object arg) {
            if ((this.SendapproveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendapproveCompleted(this, new SendapproveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Submitapprove", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Submitapprove(string id_petition_information, string jsonString) {
            object[] results = this.Invoke("Submitapprove", new object[] {
                        id_petition_information,
                        jsonString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitapproveAsync(string id_petition_information, string jsonString) {
            this.SubmitapproveAsync(id_petition_information, jsonString, null);
        }
        
        /// <remarks/>
        public void SubmitapproveAsync(string id_petition_information, string jsonString, object userState) {
            if ((this.SubmitapproveOperationCompleted == null)) {
                this.SubmitapproveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitapproveOperationCompleted);
            }
            this.InvokeAsync("Submitapprove", new object[] {
                        id_petition_information,
                        jsonString}, this.SubmitapproveOperationCompleted, userState);
        }
        
        private void OnSubmitapproveOperationCompleted(object arg) {
            if ((this.SubmitapproveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitapproveCompleted(this, new SubmitapproveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/approve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string approve(string id_petition_information) {
            object[] results = this.Invoke("approve", new object[] {
                        id_petition_information});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void approveAsync(string id_petition_information) {
            this.approveAsync(id_petition_information, null);
        }
        
        /// <remarks/>
        public void approveAsync(string id_petition_information, object userState) {
            if ((this.approveOperationCompleted == null)) {
                this.approveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnapproveOperationCompleted);
            }
            this.InvokeAsync("approve", new object[] {
                        id_petition_information}, this.approveOperationCompleted, userState);
        }
        
        private void OnapproveOperationCompleted(object arg) {
            if ((this.approveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.approveCompleted(this, new approveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/waterusernumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string waterusernumber(string numberpetition) {
            object[] results = this.Invoke("waterusernumber", new object[] {
                        numberpetition});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void waterusernumberAsync(string numberpetition) {
            this.waterusernumberAsync(numberpetition, null);
        }
        
        /// <remarks/>
        public void waterusernumberAsync(string numberpetition, object userState) {
            if ((this.waterusernumberOperationCompleted == null)) {
                this.waterusernumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnwaterusernumberOperationCompleted);
            }
            this.InvokeAsync("waterusernumber", new object[] {
                        numberpetition}, this.waterusernumberOperationCompleted, userState);
        }
        
        private void OnwaterusernumberOperationCompleted(object arg) {
            if ((this.waterusernumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.waterusernumberCompleted(this, new waterusernumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/view_user_water", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string view_user_water(string id_petition_information) {
            object[] results = this.Invoke("view_user_water", new object[] {
                        id_petition_information});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void view_user_waterAsync(string id_petition_information) {
            this.view_user_waterAsync(id_petition_information, null);
        }
        
        /// <remarks/>
        public void view_user_waterAsync(string id_petition_information, object userState) {
            if ((this.view_user_waterOperationCompleted == null)) {
                this.view_user_waterOperationCompleted = new System.Threading.SendOrPostCallback(this.Onview_user_waterOperationCompleted);
            }
            this.InvokeAsync("view_user_water", new object[] {
                        id_petition_information}, this.view_user_waterOperationCompleted, userState);
        }
        
        private void Onview_user_waterOperationCompleted(object arg) {
            if ((this.view_user_waterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.view_user_waterCompleted(this, new view_user_waterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/List_petition_information", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string List_petition_information(string id) {
            object[] results = this.Invoke("List_petition_information", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void List_petition_informationAsync(string id) {
            this.List_petition_informationAsync(id, null);
        }
        
        /// <remarks/>
        public void List_petition_informationAsync(string id, object userState) {
            if ((this.List_petition_informationOperationCompleted == null)) {
                this.List_petition_informationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnList_petition_informationOperationCompleted);
            }
            this.InvokeAsync("List_petition_information", new object[] {
                        id}, this.List_petition_informationOperationCompleted, userState);
        }
        
        private void OnList_petition_informationOperationCompleted(object arg) {
            if ((this.List_petition_informationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.List_petition_informationCompleted(this, new List_petition_informationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/List_Meter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string List_Meter(string idpetition) {
            object[] results = this.Invoke("List_Meter", new object[] {
                        idpetition});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void List_MeterAsync(string idpetition) {
            this.List_MeterAsync(idpetition, null);
        }
        
        /// <remarks/>
        public void List_MeterAsync(string idpetition, object userState) {
            if ((this.List_MeterOperationCompleted == null)) {
                this.List_MeterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnList_MeterOperationCompleted);
            }
            this.InvokeAsync("List_Meter", new object[] {
                        idpetition}, this.List_MeterOperationCompleted, userState);
        }
        
        private void OnList_MeterOperationCompleted(object arg) {
            if ((this.List_MeterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.List_MeterCompleted(this, new List_MeterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/List_water_applicant", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string List_water_applicant(string idpetition) {
            object[] results = this.Invoke("List_water_applicant", new object[] {
                        idpetition});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void List_water_applicantAsync(string idpetition) {
            this.List_water_applicantAsync(idpetition, null);
        }
        
        /// <remarks/>
        public void List_water_applicantAsync(string idpetition, object userState) {
            if ((this.List_water_applicantOperationCompleted == null)) {
                this.List_water_applicantOperationCompleted = new System.Threading.SendOrPostCallback(this.OnList_water_applicantOperationCompleted);
            }
            this.InvokeAsync("List_water_applicant", new object[] {
                        idpetition}, this.List_water_applicantOperationCompleted, userState);
        }
        
        private void OnList_water_applicantOperationCompleted(object arg) {
            if ((this.List_water_applicantCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.List_water_applicantCompleted(this, new List_water_applicantCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/List_details", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string List_details(string idpetition) {
            object[] results = this.Invoke("List_details", new object[] {
                        idpetition});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void List_detailsAsync(string idpetition) {
            this.List_detailsAsync(idpetition, null);
        }
        
        /// <remarks/>
        public void List_detailsAsync(string idpetition, object userState) {
            if ((this.List_detailsOperationCompleted == null)) {
                this.List_detailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnList_detailsOperationCompleted);
            }
            this.InvokeAsync("List_details", new object[] {
                        idpetition}, this.List_detailsOperationCompleted, userState);
        }
        
        private void OnList_detailsOperationCompleted(object arg) {
            if ((this.List_detailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.List_detailsCompleted(this, new List_detailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/List_authorities", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string List_authorities(string idpetition) {
            object[] results = this.Invoke("List_authorities", new object[] {
                        idpetition});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void List_authoritiesAsync(string idpetition) {
            this.List_authoritiesAsync(idpetition, null);
        }
        
        /// <remarks/>
        public void List_authoritiesAsync(string idpetition, object userState) {
            if ((this.List_authoritiesOperationCompleted == null)) {
                this.List_authoritiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnList_authoritiesOperationCompleted);
            }
            this.InvokeAsync("List_authorities", new object[] {
                        idpetition}, this.List_authoritiesOperationCompleted, userState);
        }
        
        private void OnList_authoritiesOperationCompleted(object arg) {
            if ((this.List_authoritiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.List_authoritiesCompleted(this, new List_authoritiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/List_approve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string List_approve(string idpetition) {
            object[] results = this.Invoke("List_approve", new object[] {
                        idpetition});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void List_approveAsync(string idpetition) {
            this.List_approveAsync(idpetition, null);
        }
        
        /// <remarks/>
        public void List_approveAsync(string idpetition, object userState) {
            if ((this.List_approveOperationCompleted == null)) {
                this.List_approveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnList_approveOperationCompleted);
            }
            this.InvokeAsync("List_approve", new object[] {
                        idpetition}, this.List_approveOperationCompleted, userState);
        }
        
        private void OnList_approveOperationCompleted(object arg) {
            if ((this.List_approveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.List_approveCompleted(this, new List_approveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Search_water_user", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Search_water_user(string jsonString) {
            object[] results = this.Invoke("Search_water_user", new object[] {
                        jsonString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Search_water_userAsync(string jsonString) {
            this.Search_water_userAsync(jsonString, null);
        }
        
        /// <remarks/>
        public void Search_water_userAsync(string jsonString, object userState) {
            if ((this.Search_water_userOperationCompleted == null)) {
                this.Search_water_userOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearch_water_userOperationCompleted);
            }
            this.InvokeAsync("Search_water_user", new object[] {
                        jsonString}, this.Search_water_userOperationCompleted, userState);
        }
        
        private void OnSearch_water_userOperationCompleted(object arg) {
            if ((this.Search_water_userCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Search_water_userCompleted(this, new Search_water_userCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Search_requst_instal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Search_requst_instal(string jsonString) {
            object[] results = this.Invoke("Search_requst_instal", new object[] {
                        jsonString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Search_requst_instalAsync(string jsonString) {
            this.Search_requst_instalAsync(jsonString, null);
        }
        
        /// <remarks/>
        public void Search_requst_instalAsync(string jsonString, object userState) {
            if ((this.Search_requst_instalOperationCompleted == null)) {
                this.Search_requst_instalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearch_requst_instalOperationCompleted);
            }
            this.InvokeAsync("Search_requst_instal", new object[] {
                        jsonString}, this.Search_requst_instalOperationCompleted, userState);
        }
        
        private void OnSearch_requst_instalOperationCompleted(object arg) {
            if ((this.Search_requst_instalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Search_requst_instalCompleted(this, new Search_requst_instalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/search_approve_request", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string search_approve_request(string jsonString) {
            object[] results = this.Invoke("search_approve_request", new object[] {
                        jsonString});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void search_approve_requestAsync(string jsonString) {
            this.search_approve_requestAsync(jsonString, null);
        }
        
        /// <remarks/>
        public void search_approve_requestAsync(string jsonString, object userState) {
            if ((this.search_approve_requestOperationCompleted == null)) {
                this.search_approve_requestOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsearch_approve_requestOperationCompleted);
            }
            this.InvokeAsync("search_approve_request", new object[] {
                        jsonString}, this.search_approve_requestOperationCompleted, userState);
        }
        
        private void Onsearch_approve_requestOperationCompleted(object arg) {
            if ((this.search_approve_requestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.search_approve_requestCompleted(this, new search_approve_requestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ViewGps_Location", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ViewGps_Location() {
            object[] results = this.Invoke("ViewGps_Location", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ViewGps_LocationAsync() {
            this.ViewGps_LocationAsync(null);
        }
        
        /// <remarks/>
        public void ViewGps_LocationAsync(object userState) {
            if ((this.ViewGps_LocationOperationCompleted == null)) {
                this.ViewGps_LocationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnViewGps_LocationOperationCompleted);
            }
            this.InvokeAsync("ViewGps_Location", new object[0], this.ViewGps_LocationOperationCompleted, userState);
        }
        
        private void OnViewGps_LocationOperationCompleted(object arg) {
            if ((this.ViewGps_LocationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ViewGps_LocationCompleted(this, new ViewGps_LocationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Upload_DataCompletedEventHandler(object sender, Upload_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Upload_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Upload_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SubmitCompletedEventHandler(object sender, SubmitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SubmitmeterCompletedEventHandler(object sender, SubmitmeterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitmeterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitmeterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SubmitwaterapplicantCompletedEventHandler(object sender, SubmitwaterapplicantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitwaterapplicantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitwaterapplicantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SubmitdetailsCompletedEventHandler(object sender, SubmitdetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitdetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitdetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SummitauthoritiesCompletedEventHandler(object sender, SummitauthoritiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SummitauthoritiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SummitauthoritiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SendapproveCompletedEventHandler(object sender, SendapproveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendapproveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendapproveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SubmitapproveCompletedEventHandler(object sender, SubmitapproveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitapproveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitapproveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void approveCompletedEventHandler(object sender, approveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class approveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal approveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void waterusernumberCompletedEventHandler(object sender, waterusernumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class waterusernumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal waterusernumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void view_user_waterCompletedEventHandler(object sender, view_user_waterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class view_user_waterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal view_user_waterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void List_petition_informationCompletedEventHandler(object sender, List_petition_informationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class List_petition_informationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal List_petition_informationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void List_MeterCompletedEventHandler(object sender, List_MeterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class List_MeterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal List_MeterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void List_water_applicantCompletedEventHandler(object sender, List_water_applicantCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class List_water_applicantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal List_water_applicantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void List_detailsCompletedEventHandler(object sender, List_detailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class List_detailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal List_detailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void List_authoritiesCompletedEventHandler(object sender, List_authoritiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class List_authoritiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal List_authoritiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void List_approveCompletedEventHandler(object sender, List_approveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class List_approveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal List_approveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Search_water_userCompletedEventHandler(object sender, Search_water_userCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Search_water_userCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Search_water_userCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void Search_requst_instalCompletedEventHandler(object sender, Search_requst_instalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Search_requst_instalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Search_requst_instalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void search_approve_requestCompletedEventHandler(object sender, search_approve_requestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class search_approve_requestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal search_approve_requestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ViewGps_LocationCompletedEventHandler(object sender, ViewGps_LocationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViewGps_LocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ViewGps_LocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591